/*
 * Copyright (c) 2011 - 2016, Apinauten GmbH
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without modification, 
 * are permitted provided that the following conditions are met:
 *
 *  * Redistributions of source code must retain the above copyright notice, this 
 *    list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above copyright notice, 
 *    this list of conditions and the following disclaimer in the documentation 
 *    and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND 
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED 
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. 
 * IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, 
 * INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, 
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF 
 * LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE 
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED 
 * OF THE POSSIBILITY OF SUCH DAMAGE.
 * 
 * THIS FILE IS GENERATED AUTOMATICALLY. DON'T MODIFY IT.
 */

#import <Foundation/Foundation.h>

/**
 Holds status codes for ApiOmat
 */
@interface AOMStatus : NSObject
typedef enum {
    AOMSCRIPT_ERROR = 701,
    AOMAPPLICATION_NOT_ACTIVE = 702,
    AOMBAD_IMAGE = 703,
    AOMBAD_ID = 704,
    AOMCONCURRENT_ACCESS = 705,
    AOMAPPLICATION_SANDBOX = 706,
    AOMMODEL_NOT_DEPLOYED = 707,
    AOMWRONG_REF_TYPE = 709,
    AOMATTRIBUTE_NOT_SET = 710,
    AOMOPERATION_NOT_POSSIBLE = 711,
    AOMAPPLICATION_NAME_MISMATCH = 712,
    AOMWRONG_AUTH_HEADER = 713,
    AOMMODEL_STILL_USED = 714,
    AOMCOLLECTION_NOT_ALLOWED = 715,
    AOMFB_NO_VALID_MEMBER = 716,
    AOMFB_NO_OAUTH_TOKEN = 717,
    AOMFB_POST_ID_MISSING = 718,
    AOMRESTORE_NO_DUMPS_FOUND = 719,
    AOMTW_NO_VALID_MEMBER = 720,
    AOMTW_NO_OAUTH_TOKEN = 721,
    AOMIMEXPORT_WRONG_ENCODING = 722,
    AOMIMEXPORT_WRONG_CONTENT = 723,
    AOMPUSH_PAYLOAD_EXCEEDED = 724,
    AOMPUSH_ERROR = 725,
    AOMBAD_EMAIL = 726,
    AOMBAD_PROMOTIONCODE_DISCOUNT = 727,
    AOMBAD_PROMOTIONCODE_CODE = 728,
    AOMPLAN_PRICE = 729,
    AOMPLAN_NO_SYSTEMS = 730,
    AOMSCRIPT_TIME_ERROR = 731,
    AOMINVALID_NAME = 732,
    AOMATTRIBUTE_IN_SUPERCLASS = 733,
    AOMJSON_TYPE_ERROR = 734,
    AOMTBLR_NO_VALID_MEMBER = 735,
    AOMTBLR_NO_OAUTH_TOKEN = 736,
    AOMTBLR_POST_ID_MISSING = 737,
    AOMLOCATION_INVALID = 738,
    AOMSCRIPT_EXCEPTION = 739,
    AOMBAD_ACCOUNTNAME = 740,
    AOMBAD_IMAGE_ALPHA = 746,
    AOMBAD_IMAGE_BGCOLOR = 747,
    AOMBAD_IMAGE_FORMAT = 748,
    AOMQUERY_ERROR = 708,
    AOMBAD_TYPE_IN_QUERY = 741,
    AOMUNKNOWN_CLASS_IN_QUERY = 742,
    AOMWRONG_NUM_FORMAT_IN_QUERY = 743,
    AOMQUERY_PARSE_ERROR = 744,
    AOMUNKNOWN_ATTRIBUTE_IN_QUERY = 745,
    AOMFOREIGNID_NOT_SET = 749,
    AOMCLASSES_MISSING = 750,
    AOMINVALID_ATTRIBUTE_TYPE = 751,
    AOMTOKEN_VALUE_EXISTS = 752,
    AOMJSON_FORMAT_ERROR = 753,
    AOMMODULE_DEPLOYMENT = 754,
    AOMBAD_USERNAME = 755,
    AOMCSV_ZIP_FORMAT = 756,
    AOMVERIFICATION = 757,
    AOMMODULE_STILL_USED = 758,
    AOMCLASS_NOT_IN_MODULE = 759,
    AOMORDER_TRANSACTION_TIMESTAMP_OUTDATED = 760,
    AOMORDER_TRANSACTION_ID_INVALID = 761,
    AOMORDER_TRANSACTION_SECRET_INVALID = 762,
    AOMMANDATORY_FIELD = 763,
    AOMINVALID_PASSWD_LENGTH = 764,
    AOMBAD_PROMOTIONCODE_VALID = 765,
    AOMBAD_CLASS_NAME_SAME_AS_MODULE = 766,
    AOMNO_ORG_MEMBER = 767,
    AOMMODULE_CLASS_NOT_CONTAINED = 768,
    AOMBAD_GROUP_NAME = 769,
    AOMAPPLICATION_NOT_FOUND = 801,
    AOMCUSTOMER_NOT_FOUND = 802,
    AOMID_NOT_FOUND = 803,
    AOMMODEL_NOT_FOUND = 804,
    AOMMODULE_NOT_FOUND = 805,
    AOMMETAMODEL_NOT_FOUND = 806,
    AOMPLAN_NOT_FOUND = 807,
    AOMPROMOCODE_NOT_FOUND = 808,
    AOMDEMOAPP_NOT_FOUND = 809,
    AOMORGANIZATION_NOT_FOUND = 810,
    AOMGROUP_NOT_FOUND = 811,
    AOMACCOUNT_NOT_FOUND = 812,
    AOMDEFAULT_MODULE_NOT_FOUND = 813,
    AOMMODULE_USE_FORBIDDEN = 820,
    AOMPUSH_ERROR_APIKEY = 821,
    AOMPUSH_ERROR_CERTIFICATE = 822,
    AOMSAME_NAME_USED_IN_SUPERCLASS = 823,
    AOMPAYMENT_MAX_MODULE = 824,
    AOMPAYMENT_SYSTEM = 825,
    AOMPAYMENT_DOWNGRADE = 826,
    AOMSAVE_REFERENECE_BEFORE_REFERENCING = 827,
    AOMPAYMENT_DB_SIZE = 828,
    AOMENDPOINT_PATH_NOT_ALLOWED = 829,
    AOMPAYMENT_NO_CRON = 1820,
    AOMPAYMENT_MODULE_NOT_FREE = 1821,
    AOMNATIVEMODULE_DEACTIVATED = 1822,
    AOMLICENSE_INVALID = 1823,
    AOMPAYMENT_NO_CUSTOMERROLES = 1824,
    AOMWHITELABEL = 1825,
    AOMWHITELABEL_NOT = 1826,
    AOMMODULE_CONFIG_NO_DOT = 1827,
    AOMPLAN_FALLBACK = 1828,
    AOMPLAN_INACTIVE = 1829,
    AOMENTERPRISE = 1830,
    AOMACCOUNT_UNACCEPTED_CONTRACTS = 1831,
    AOMDELETE_MANDATORY_DEFAULT_MODULE = 1832,
    AOMID_EXISTS = 830,
    AOMNAME_RESERVED = 831,
    AOMCIRCULAR_DEPENDENCY = 832,
    AOMNAME_EXISTS = 833,
    AOMEMAIL_EXISTS = 834,
    AOMCUSTOMER_IN_ORG = 835,
    AOMUNAUTHORIZED = 840,
    AOMWRONG_APIKEY = 841,
    AOMEVALANCHE_UNAUTH = 842,
    AOMPW_CHANGE_W_TOKEN = 843,
    AOMTOKEN_AUTH_ERROR = 844,
    AOMTOKEN_READ_ONLY = 845,
    AOMCRUD_ERROR = 901,
    AOMIMEXPORT_ERROR = 902,
    AOMCOMPILE_ERROR = 903,
    AOMREFERENCE_ERROR = 904,
    AOMPUSH_PAYLOAD_ERROR = 905,
    AOMPUSH_SEND_ERROR = 906,
    AOMPUSH_INIT_FAILED = 907,
    AOMFACEBOOK_ERROR = 908,
    AOMFACEBOOK_OAUTH_ERROR = 910,
    AOMFACEBOOK_OAUTH_ERROR2 = 917,
    AOMMEMBER_NOT_FOUND = 911,
    AOMWORDPRESS_FETCH_DATA_ERROR = 912,
    AOMTUMBLR_OAUTH_ERROR = 913,
    AOMTUMBLR_ERROR = 914,
    AOMEXECUTE_METHOD_ERROR_PRIMITIVE = 915,
    AOMEXECUTE_METHOD_ERROR = 916,
    AOMOAUTH_TOKEN_REQUEST_ERROR = 918,
    AOMFINDING_RESOURCE_ERROR = 919,
    AOMNATIVEMODULE_DEPLOY = 920,
    AOMTOKEN_SEARCH_ERROR = 921,
    AOMMODULE_CONFIG_MISSING = 922,
    AOMNATIVEMODULE_INIT = 923,
    AOMNATIVEMODULE_PULL = 924,
    AOMNATIVEMODULE_PUSH = 925,
    AOMNO_DOGET_RETURN = 926,
    AOMCUSTOMER_TWO_ORGS = 927,
    AOMNATIVEMODULE_HOOKS_NOT_FOUND = 928,
    AOMANALYTICS_ERROR = 929,
    AOMEMAIL_ERROR = 930,
    AOMHREF_NOT_FOUND = 601,
    AOMWRONG_URI_SYNTAX = 602,
    AOMWRONG_CLIENT_PROTOCOL = 603,
    AOMIO_EXCEPTION = 604,
    AOMUNSUPPORTED_ENCODING = 605,
    AOMINSTANTIATE_EXCEPTION = 606,
    AOMIN_PERSISTING_PROCESS = 607,
    AOMVERIFY_SOCIALMEDIA = 608,
    AOMTOO_MANY_LOCALIDS = 609,
    AOMMAX_CACHE_SIZE_REACHED = 610,
    AOMCANT_WRITE_IN_CACHE = 611,
    AOMBAD_DATASTORE_CONFIG = 612,
    AOMNO_TOKEN_RECEIVED = 613,
    AOMNO_NETWORK = 614,
    AOMID_NOT_FOUND_OFFLINE = 615,
    AOMATTACHED_HREF_MISSING = 616,
    AOMREQUEST_TIMEOUT = 617,
    AOMASYNC_WAIT_ERROR = 618,
    AOMIN_DELETING_PROCESS = 619,
    AOMSSO_REDIRECT = 620,
    AOMMANUAL_CONCURRENT_WRITE_FAILED = 621,
    AOMSAVE_FAILED = 622,
    AOMMALICIOUS_MEMBER = 950,
} AOMStatusCode;

/*!
 Returns human readable phrase for given status code
 @param _code an enum for which we need the phrase
 @return the phrase for this given AOMStatusCode
 */
+ (NSString*) getReasonPhraseForCode: (AOMStatusCode) _code;
/*!
 Get AOMStatusCode for given integer _code
 @param _code Given integer (mostly returned from HTTP response)
 @return AOMStatusCode an enum
 */
+ (AOMStatusCode) getStatusForCode: (NSInteger) _code;
@end